### ISSUE TITLE
deb file not able to download

### ISSUE THREAD

**Issue by aphive** [hydruid/zenoss#31]
Getting this issue as well....

wget -N http://softlayer-dal.dl.sourceforge.net/project/zenossforubuntu/zenoss-core-425-2108_03c_amd64.deb
--2016-01-06 22:40:19--  http://softlayer-dal.dl.sourceforge.net/project/zenossforubuntu/zenoss-core-425-2108_03c_amd64.deb
Resolving softlayer-dal.dl.sourceforge.net (softlayer-dal.dl.sourceforge.net)... failed: Name or service not known.
wget: unable to resolve host address ‘softlayer-dal.dl.sourceforge.net’

**Comment by Computero** [comment]
I did find it here tho:

http://sourceforge.net/projects/zenossforubuntu/files/zenoss-core-425-2108_03c_amd64.deb

**Comment by hydruid** [comment]
The issue is that the script wasn't downloading the deb that's why
everything wasn't found. Manually update the link.

I abandoned that project years ago and started using zabbix.

**Comment by Computero** [comment]
How do you like Zabbix and how does it compare to Zenoss?

**Comment by hydruid** [comment]
I really like Zabbix. Their documentation and examples are epic,
installation is super easy (even from source), distributed collecting is a
breeze, and I don't have to spend hours everyday fixing things like I did
with zenoss.

I will never use zenoss again lolol.

**Comment by Computero** [comment]
Thanks, I'll check that out instead.
