### ISSUE TITLE
Default Autodeploy ZenPacks

### ISSUE THREAD

**Issue by aalvrz** [hydruid/zenoss#34]
I am trying to find where and when the default ZenPacks are installed in this auto deploy script. I am talking about ZenPacks such as `ZenPacks.zenoss.ActiveDirectory`, `ZenPacks.zenoss.ApacheMonitor`, `ZenPacks.zenoss.HttpMonitor`, etc.

After reading through the scripts, it seems these ZenPacks are listed in a file called `$ZENHOME/var/zenpack_actions.txt`. Strangely, I cannot find  this file in this repository. I did however [find it](https://github.com/zenoss/core-autodeploy/blob/4.2.5/zenpack_actions.txt) in the original Zenoss's CentOS auto deployment script.

Would really like some  guidance on where I can find this file or the list of default ZenPacks for this Ubuntu autodeploy, as I would like to modify which ZenPacks are installed in the Core by the default.

**Comment by krull** [comment]
@BigChief45 the deb file that @hydruid provides contains the default ZenPacks, albiet outdated. The scripts here does not do the auto install of ZenPacks. It is implied.

@krull

**Comment by BigChief45** [comment]
@krull Thank you for your answer.

Do you happen to know where inside the deb package the ZenPacks are installed? I can see all the ZenPack eggs in `/usr/local/zenoss/ZenPacks'` directory inside the deb file. However, I tried removing them, re-packaging and re-installing Zenoss. The ZenPacks are somehow **_still_** installed.
